name: lifecompanion_mobile
description: 'LifeCompanion - Assistant Environnemental Personnel Mobile'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Interface utilisateur
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1

  # Gestion d'état (Bloc Pattern)
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.2

  # Networking & API
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # WebSocket & Temps réel
  web_socket_channel: ^2.4.0
  mqtt_client: ^10.2.0

  # Base de données locale
  sqflite: ^2.3.0
  path: ^1.8.3

  # Stockage local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Notifications
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.9

  # Géolocalisation
  geolocator: ^10.1.0
  permission_handler: ^11.2.0

  # Graphiques et visualisations
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.2.9

  # Utilitaires dates
  intl: ^0.19.0
  timezone: ^0.9.2

  # Utilities
  get_it: ^7.6.7
  injectable: ^2.3.2
  auto_route: ^7.9.2
  freezed_annotation: ^2.4.1

  # Logging & Debug
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7

  # Linting
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

  # Fonts personnalisées
  fonts:
    - family: LifeCompanion
      fonts:
        - asset: assets/fonts/LifeCompanion-Regular.ttf
        - asset: assets/fonts/LifeCompanion-Bold.ttf
          weight: 700

# Configuration des icônes de l'app
flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/app_icon.png'
  min_sdk_android: 21
  web:
    generate: true
    image_path: 'assets/icon/app_icon.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/icon/app_icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon/app_icon.png'
